# Generated by Django 5.2.6 on 2026-05-01 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('language_requirement', models.CharField(blank=True, max_length=200)),
                ('available_slots', models.PositiveIntegerField(default=5)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('min_gpa', models.DecimalField(decimal_places=2, default=3.0, max_digits=3)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Partner Universities',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('student_id', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=50)),
                ('passport_expiry', models.DateField()),
                ('current_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('program', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate')], max_length=20)),
                ('academic_level', models.CharField(max_length=100)),
                ('exchange_semester', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], max_length=10)),
                ('exchange_year', models.PositiveIntegerField()),
                ('transcript', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('passport_copy', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('personal_statement', models.TextField()),
                ('language_proficiency', models.CharField(max_length=200)),
                ('reference_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('first_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_choice_applications', to='iseo.partneruniversity')),
                ('second_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_choice_applications', to='iseo.partneruniversity')),
            ],
        ),
    ]
